ExperimentData.store documentation is not correct
bessagroup/f3dasm pull request #203
Opened 2023-10-26 20:52 UTC by mpvanderschelling

Fixes #190

2023-10-26 20:54 UTC, mpvanderschelling commented
Also I changed the order of the ExperimentSample.store() method so that the name is the first argument.
This resembles other methods where a name is provided i.e. Domain.add_float(name, low, high)

2023-10-27 14:04 UTC, BernardoFerreira requested changes
Docstrings of methods to save data to files should always be clear about where the data is being stored (directory and file).

Please clarify this in both ExperimentData and ExperimentSample store methods.

2023-10-27 14:04 UTC, BernardoFerreira commented on src/f3dasm/_src/experimentdata/experimentsample.py
> +    def store(self, name: str, object: Any, to_disk: bool = False,
Please clarify in the method docstring where the object is actually stored.

As far as I can understand from the documentation, the user is only providing the basename of the storage file.

2023-10-27 14:04 UTC, BernardoFerreira commented on src/f3dasm/_src/experimentdata/experimentdata.py
> +    def store(self, filename: Optional[str] = None):
Please clarify in the method docstring where the object is actually stored.

2023-10-27 15:52 UTC, mpvanderschelling commented
I accidentally removed a comment from you Bernardo

2023-10-27 17:14 UTC, BernardoFerreira approved these changes

2023-10-27 19:03 UTC, merged